name: WPF CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --configuration Release --no-restore

      - name: Run Unit Tests
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Publish Application
        run: |
          dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o ./publish
          
      - name: Create Git Tag
        run: |
          git tag -a v$(date +'%Y%m%d%H%M%S') -m "Automated release"
          git push origin v$(date +'%Y%m%d%H%M%S')

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./publish/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
